### ISSUE TITLE
Pin item doesn't work

### ISSUE THREAD

**Issue by z-zane** [Dominic-DallOsto/zotero-pin-items#3]
I add this plugin to my Zotero 7, but it does not show up in setting and right click menu. Then I disabled other plugins, but it still does not work.

**Comment by hello-ppareja** [comment]
same problem

**Comment by kokoroshima** [comment]
same problem

**Comment by huachuman** [comment]
yea... nothing happens.

**Comment by Dominic-DallOsto** [comment]
I think this might be the same issue as https://github.com/Dominic-DallOsto/zotero-reading-list/issues/58

Does the [v0.1.2](https://github.com/Dominic-DallOsto/zotero-pin-items/releases/tag/v0.1.2) release fix this for you?

**Comment by huachuman** [comment]
now it adds a pin to the item but the sort column still won't put pinned items at the top

**Comment by z-zane** [comment]
Yes, I have tried the newest version, however, it still can not pin the item while it shows up in right click menu. @Dominic-DallOsto

**Comment by Dominic-DallOsto** [comment]
@huachuman @z-zane Thanks for the response! Could you create new issues for these other problems - just to keep everything a bit more organised. If you could add screenshots or recordings of the issues that would be really helpful!

**Comment by huachuman** [comment]
I mean does the extension work for you? You're asking for recordings but I'm not sure what to record when nothing works...

**Comment by Dominic-DallOsto** [comment]
Yeah, it's working for me - that's why I need more information from you to try and fix the issue.

Basically, if you go through the steps [here](https://github.com/Dominic-Dallosto/zotero-pin-items?tab=readme-ov-file#how-to-use) where do you fail?

I think the original issue described here was caused by an incompatibility loading the extension, so nothing would show up at all (ie. step 1 would fail). For me, this is fixed now.

When you say that you pin it and it doesn't go anywhere - does the pin icon show up for the item, but the sorting doesn't change? Or does the pin icon not show up at all? Are you trying to pin it in a collection or in you main library? Or is this is a shared library? Which operating system and version of Zotero are you using? Do you see anything shown in the "Extra" field of the item? Do any errors occur in the error console (Tools > Developer > Error Console).

**Comment by huachuman** [comment]
Ah! Got it. So this is only intended for use with Collections, and doesn't work with the library right now, is that right?

**Comment by Dominic-DallOsto** [comment]
v0.1.2 should also work in the main library, while older versions only worked in collections. But yeah, the pinning is handled separately for each collection, so pinning an item in one collection doesn't pin it in any other collections the item might also be a part of.

**Comment by huachuman** [comment]
Ok interesting. Thanks so much for the update!

I think I might be experiencing some issues because my library has so many items that don't have complete metadata. In case you're wondering, this is what I get in the library pane when I pin items (with secondary sort as Date Added)

![image](https://github.com/user-attachments/assets/643e2259-a5f4-484a-9685-a073176faf72)

**Comment by Dominic-DallOsto** [comment]
So if you click on the pin column header to change the sort order, the items you see as pinned don't go to the top or bottom, but stay in the middle?

Does the same happen if you try this in a collection with fewer items?

**Comment by huachuman** [comment]
Yea exactly. 

Actually I just noticed all the items above it don't have "parent items" - i.e. they're all pdfs and other files like .txt and .jpg with no parent.

**Comment by z-zane** [comment]
> So if you click on the pin column header to change the sort order, the items you see as pinned don't go to the top or bottom, but stay in the middle?
> 
> Does the same happen if you try this in a collection with fewer items?

Yes, that is exactly what happened in my Zotero. And my collection is full of parent items.

**Comment by Dominic-DallOsto** [comment]
@huachuman Ahh OK. In that case it's kind of expected, because it's not possible to pin raw attachments without parent items. Can you describe how you would like the sorting to be vs how it is at the moment?

@z-zane Could you post a picture of what is happening? If you have all parent items in your collection and sorting by pinned items isn't worked then it sounds like there's a bug

**Comment by huachuman** [comment]
I keep my library sorted as Date Added. The raw attachment items sort just fine like this until I introduce the pin sorting. Ideally the pins would show up at the very top, above all attachments.

I'm considering giving those raw attachments parent items, but there is some contemplation to do before going in that direction seeing as I have thousands of them.

**Comment by Dominic-DallOsto** [comment]
I just added some options for changing the sort order in the latest version ([v0.3.0](https://github.com/Dominic-DallOsto/zotero-pin-items/releases/tag/v0.3.0))- let me know if this fixes your problem!

**Comment by z-zane** [comment]
Unfortunately, it shows this latest version of the plugin is incompatible with Zotero 7

**Comment by Dominic-DallOsto** [comment]
Because of some recent Zotero changes, it's only compatible with v7.0.10 of Zotero.

If you update does the new version of the extension work for you?

**Comment by z-zane** [comment]
Thanks! Em...After I update Zotero, it can be installed. However, it shows pin item menu only when click parent items and for these items it still doesn't work, while other items such as standalone notes do not have the option

**Comment by Dominic-DallOsto** [comment]
Yes, it's only possible to pin parent items, not standalone notes or standalone files, because parent items are the only place we can add metadata for which items are pinned.

The update just added options in the Edit > Settings menu for whether you want standalone files or notes to appear above or below pinned items.

"For these items it still doesn't work" - what exactly do you mean? If you click the button the items don't get pinned?

**Comment by z-zane** [comment]
Yes, I have tried it to pin patrent items, but nothing happened

**Comment by Dominic-DallOsto** [comment]
A few things to check:
* Do you have the pinned items column enabled?
* After you pin an item and them right click it again, do you see the option to unpin the item, or still to pin it?
* Can you check the Zotero error console for any error messages that occur when you try to pin items?
* Can you check the item's Extra field after you try to pin it? Do you see anything in there?

**Comment by z-zane** [comment]
Oh, I see. I haven't had the pinned items column enabled. Now I have no other problems.
It is so kind of you. Thank you very much.

**Comment by huachuman** [comment]
Looks like the update solved the issue, at least at first glance. Pinned items now properly float to the top regardless of whether there are orphan items in my library. 

Superb job. Very necessary plugin for anyone that uses literature often. Zotero should have built something like this in by default a long time ago.
