### ISSUE TITLE
No pin item shown in the panel

### ISSUE THREAD

**Issue by byji** [Dominic-DallOsto/zotero-pin-items#4]
After update to 0.1.2, the pin item is disappeared from the column list and the panel.
If go back to the 0.1.0 version, the pin item appeared, but can not pin any paper on the top of the list

**Comment by Dominic-DallOsto** [comment]
Just to check - which version of Zotero are you using?

**Comment by byji** [comment]
Thanks.
version 7.0.10-beta.3+56ae6d979

**Comment by Dominic-DallOsto** [comment]
Ahh cool OK. Zotero 7.0.10 had a change in the API that broke this plugin. It should be fixed by https://github.com/Dominic-DallOsto/zotero-pin-items/commit/c8446b2b2715979083128c2834922b3f418a4f71 in [v0.2.0](https://github.com/Dominic-DallOsto/zotero-pin-items/releases/tag/v0.2.0).

Let me know if the plugin updating through the Zotero plugin manager works for you because I had to set it to only work for Zotero 7.0.10 and above now!

**Comment by byji** [comment]
Thanks.
It is working now
